# Generated by Django 3.2 on 2021-04-25 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaBoard', '0002_auto_20210425_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена (грн)'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес (г)'),
        ),
    ]
