# Generated by Django 3.2 on 2021-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaBoard', '0004_auto_20210503_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pizza',
            new_name='pizzas',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
